name: 'ww'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: mario
      POSTGRES_DB: nestBackend
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    network_mode: host

  frontend:
    build:
      context: .
      dockerfile: ./deploy/frontend/Dockerfile
    ports:
      - '3000:3000'
    network_mode: host
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend/Dockerfile
    ports:
      - '4000:4000'
    network_mode: host
    depends_on:
      - db
