services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: mario
      POSTGRES_DB: nestBackend
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
